### ISSUE TITLE
Add federation support

### ISSUE THREAD

**Issue by alanking** [irods/irods_testing_environment#10]
At least two iRODS zones should be able to be federated. This can either be a docker-compose project or a way of manually stitching together existing docker-compose projects and executing logic which federates the zones together. Or perhaps both. The important thing, I think, is for each zone to be composed of more than just a catalog service provider but should each be a set of iRODS servers a la existing docker-compose projects which include catalog service consumers.

**Comment by trel** [comment]
if only we had a way to describe a federation already.... like... a zone_report or something...

**Comment by alanking** [comment]
I will leave this open until the zone_report magic wand is real

**Comment by alanking** [comment]
Also make sure that `--use-ssl` works with federate.py script

**Comment by alanking** [comment]
The zone report thing should be considered its own effort. I've created an issue for that here: https://github.com/irods/irods_testing_environment/issues/239 Closing this one.
