### ISSUE TITLE
Add rockylinux:8 support

### ISSUE THREAD

**Issue by alanking** [irods/irods_testing_environment#116]
This platform can run our RPM packages and is popular among users, so we might as well support it here

**Comment by trel** [comment]
Closed!  In the aisle between the iRODS Booth and the RockyLinux Booth at SC22!

![C8DDDB18-2247-45DF-9414-849F98092E04](https://user-images.githubusercontent.com/55238/202866214-d8d1845a-41fe-4a03-a473-10919fd25874.jpeg)
