### ISSUE TITLE
Add more recent version(s) of Postgres for all platforms

### ISSUE THREAD

**Issue by alanking** [irods/irods_testing_environment#165]
The only version of Postgres that we have right now is 10.12. Postgres 10 was declared EOL in October 2022 (from https://www.postgresql.org/support/versioning/):
> After its five year anniversary, a major version will have one last minor release containing any fixes and will be considered end-of-life (EOL) and no longer supported. 

The latest version at time of writing is 15. It seems that 16 will be released in Fall 2023. Please investigate and find the latest version we can use for testing.

- [ ] AlmaLinux 8
- [ ] Rocky Linux 8
- [x] Ubuntu 20.04

Newer platforms that we will support will only support newer versions of Postgres.

**Comment by trel** [comment]
alma8 and rocky8?  checkboxes?

**Comment by SwooshyCueb** [comment]
I can't check them, alan will have to

**Comment by trel** [comment]
i can do it!

**Comment by trel** [comment]
I have checked them.    Although, i didn't see those commits linked here... so I assume they are included elsewhere?

**Comment by SwooshyCueb** [comment]
It was in #213, and linked to irods/irods#7382

**Comment by trel** [comment]
Got it.   Thanks.
