### ISSUE TITLE
Add mariadb projects

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_testing_environment#167]
There is at least one consortium member using mariadb, so let's add mariadb projects.
~~We should add 10.3 (mysql 5.7 compat) and 10.11 (latest mysql 8.0 compat) projects.~~
I think we should add projects for 10.11 (present in Debian 12 repos and the most-recent lts version) at the very least, and also consider 10.6 (present in Ubuntu 22.04 repos) ~~and 10.5 (present in EL8, EL9, Debian 11 repos)~~.

Edit 2024-05-15: The upcoming MariaDB 11.4 has been declared LTS. If 11.4 has been released by the time work starts on this issue, projects should be added for 11.4 as well.

**Comment by korydraughn** [comment]
iRODS 4.3 requires MySQL 8+, so I believe we only need to support MariaDB 10.11+.

**Comment by SwooshyCueb** [comment]
For our mysql projects, we pass `--transaction-isolation=READ-COMMITTED --collation-server=utf8mb4_0900_as_cs --disable-log-bin` to the mysql server.

The closest equivalent for mariadb 10.6 is `--transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --disable-log-bin`
The closest equivalent for mariadb 10.11 is `--transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_uca1400_as_cs --disable-log-bin`

**Comment by korydraughn** [comment]
Sounds reasonable to me.
