### ISSUE TITLE
Remove mysql 5.7 projects

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_testing_environment#169]
Given that 4.2 has seen its last release and 4.3 requires UTF-8 in the db, we can remove the mysql 5.7 projects now.

**Comment by korydraughn** [comment]
What's the recommendation for people needing to test/use a version of 4.2?

It's not uncommon to spin up an earlier version of iRODS to compare behavior. I think 4.2 only works with MySQL 5.7.

**Comment by SwooshyCueb** [comment]
My recommendation would be to check out the commit before 5.7 is removed.

**Comment by korydraughn** [comment]
That's fine given we use git.

Perhaps we should apply a tag to mark where 4.2 support ends. Then no one has to search for the commit if they need it.

Thoughts?

**Comment by trel** [comment]
That seems useful.

No new 4.2-specific things are expected to ever land here, so marking our current tip of main as `4.2-end-of-support` (or something similar) seems okay/good.

Please suggest tag-names here...

**Comment by trel** [comment]
we should consider the same for https://github.com/irods/irods_development_environment/

**Comment by korydraughn** [comment]
The tag you suggested seems fine. Alternatively we use the abbreviated form (i.e. `4.2-EOL`) with the assumption that many devs tend to use EOL as a search term.

**Comment by trel** [comment]
`4.2-EOL` seems fine.   Have to make sure it’s not confusing which commit is the last good one vs the first one that breaks compatibility.

**Comment by korydraughn** [comment]
I'm fine with the one you came up with. All we need is a small section in the README that explains the scheme used for EOL/EOS.

**Comment by trel** [comment]
Agreed.   We’ve almost done this for past releases / thresholds but it was never clear as we added new externals before we knew an older thing was going away or already didn’t work as expected.
