### ISSUE TITLE
modify_script uses a variable declared outside of the function

### ISSUE THREAD

**Issue by alanking** [irods/irods_testing_environment#188]
This seems to work since the `univmss_script` variable is declared in the function containing this function, but we should really use the `script` parameter to be correct:
https://github.com/irods/irods_testing_environment/blob/a61cd7a6afc776c9fe82ecfce177ca85d5b6f631/irods_testing_environment/irods_config.py#L279-L283

**Comment by trel** [comment]
that's weird.   it's always been this way?

**Comment by alanking** [comment]
It probably became this way when adding parallel-ism to the test suite. Like I said, it seems to work, but that's just coincidental here. Also, the run_tests.py script also seems to do this work, so it really doesn't matter that much in the end.
