### ISSUE TITLE
Create tag to indicate removal of Ubuntu 16 and 18

### ISSUE THREAD

**Issue by alanking** [irods/irods_testing_environment#207]
Ubuntu 16 and 18 are being removed: https://github.com/irods/irods_testing_environment/pull/206

Let's push a tag to indicate this in case we need to go back in time to an older version on one of these platforms.

**Comment by SwooshyCueb** [comment]
Previous discussion about tagging is in #169

**Comment by alanking** [comment]
Ah, good. Thanks

**Comment by alanking** [comment]
So we will want to tag this commit: f2cfbd835868a56671e10f264d8c4403a7ed6570 The name of the tag should be `4.2-EOL`.

**Comment by korydraughn** [comment]
See the tags in the development environment. Use the same format.

**Comment by alanking** [comment]
If we are going to follow the format of the development environment, it seems we will need... 3 or 4 tags?
- `EOL-42stable-ubuntu16`
- `EOL-42stable-ubuntu18`
- `EOL-43stable-ubuntu18`

I'm not sure that the branch name has much merit in this repo, so maybe just two:
- `EOL-ubuntu16`
- `EOL-ubuntu18`

**Comment by korydraughn** [comment]
That makes sense.

**Comment by trel** [comment]
Agreed.

**Comment by alanking** [comment]
I'll try to get this done today. Just to be completely clear, here's what I'm proposing...

f2cfbd835868a56671e10f264d8c4403a7ed6570 will be tagged as `EOL-ubuntu16`
8f64004dfa86bd6cf0050324850fcebe599d1b4e will be tagged as `EOL-ubuntu18`
a9a307a4d9b05ac419ea4d737d55fcff3d0119af will be tagged as `EOL-mysql5`

```bash
$ git show --oneline -s main~4..main
e4c1eed (HEAD -> main, upstream/main, origin/main, origin/HEAD) [#169] Remove mysql 5.7
a9a307a [#205] Remove Ubuntu 18.04
8f64004 [#168] Remove Ubuntu 16.04
f2cfbd8 [#203] Ensure all required packages can be found
```

**Comment by trel** [comment]
makes sense - tagging the last known good sha for each.

**Comment by alanking** [comment]
Good. Tags pushed. Closing.
