### ISSUE TITLE
Remove/replace postgres 10 projects

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_testing_environment#212]
PostgreSQL 10's last release was November 10, 2022.
Every distribution we support (except EL7) provides PostgreSQL 12 or newer.
I do not think there is any value in continuing to test against this old version of PostgreSQL.
Let's remove our PostgreSQL 10 projects. We will also need to add Debian 11 and EL8 projects for newer versions of PostgreSQL.

**Comment by korydraughn** [comment]
Agreed.
