### ISSUE TITLE
Use MySQL 8 ODBC drivers for MariaDB

### ISSUE THREAD

**Issue by korydraughn** [irods/irods_testing_environment#223]
Using a modified build of the testing environment, I was able to watch all unit tests and core tests pass for an iRODS server with MariaDB 11.4.

The key to this was:
- Using the MySQL 8.0.33 ODBC driver
    - I modified odbc_setup.py to download the MySQL 8 ODBC driver when launching MariaDB 11.4
    - The MariaDB ODBC driver appears to have a bug related to the use of `SQLRowCount`
- Passing the following command line options to MariaDB _(in the docker-compose.yml file)_
    - `--transaction_isolation=READ-COMMITTED`
    - `--character_set_server=utf8mb4`
    - `--collation_server=utf8mb4_bin`

The testing environment needs to be updated to use the MySQL 8 ODBC drivers until we find a suitable MariaDB ODBC driver.

**Comment by korydraughn** [comment]
I only tried this with the MySQL 8.0.33 ODBC driver, but I believe the outcome would be the same if some other version of the MySQL 8 ODBC driver were used (e.g. v8.4.x).

**Comment by alanking** [comment]
Related to https://github.com/irods/irods_testing_environment/issues/223

**Comment by SwooshyCueb** [comment]
I'll take care of this today

**Comment by SwooshyCueb** [comment]
> The MariaDB ODBC driver appears to have a bug related to the use of `SQLRowCount`

Their issue tracker is [here](https://jira.mariadb.org/projects/ODBC/issues/) if you want to open an issue about it (if there isn't one already).

**Comment by korydraughn** [comment]
Will take a look.
