### ISSUE TITLE
run_plugin_tests does not copy out xmlrunner reports

### ISSUE THREAD

**Issue by d-w-moore** [irods/irods_testing_environment#30]
- [x] main
- [x] 4-2-stable
---
These results (*.xml) are usually in `/var/lib/irods/test-reports` at the time the tests are finished.

**Comment by alanking** [comment]
Ready for checkboxes and closing, I think?

**Comment by alanking** [comment]
Let's reopen this to fix the confusing error messages

**Comment by alanking** [comment]
Nevermind, see #35. 🤡
