### ISSUE TITLE
Improve test result presentation

### ISSUE THREAD

**Issue by alanking** [irods/irods_testing_environment#66]
The `test_runner` and `test_manager` result strings could be improved. The timestamps in the recently added duration trackers are inconsistent in precision and spacing. There are probably other things that could be improved as well. Use your imagination :)

**Comment by trel** [comment]
https://docs.python.org/3/library/string.html#format-specification-mini-language

**Comment by alanking** [comment]
Possibly bound up with #47

**Comment by alanking** [comment]
I think this is now done.

**Comment by trel** [comment]
looks like it - #47 is independent i think.

**Comment by alanking** [comment]
Neat
