### ISSUE TITLE
Add configuration for test_auth

### ISSUE THREAD

**Issue by alanking** [irods/irods_testing_environment#89]
`test_auth` requires that a user exists with name 'irodsauthuser' and password ';=iamnotasecret'. This can be done as part of the configuration for testing along with configuring the univMSS script and whatnot

**Comment by korydraughn** [comment]
This should be documented in the README unless it is obvious to the user.

**Comment by alanking** [comment]
Which README are you referring to? Come to think of it, we should probably come up with some words about running the iRODS test suite somewhere...

**Comment by korydraughn** [comment]
In this repo's README. It can be in a separate markdown file within this repo if you feel that is better.

And yes, I agree we should have words that show how to run the test suite, etc.

All of that information should be in this repo. We can reference this repo from other places (e.g. docs.irods.org), but those other places do not need to go into much detail about how to run a test, etc.

**Comment by alanking** [comment]
Okay, I can make an issue for that.

For what it's worth, this feature in particular does not need any instructions unless you just wanted to note it for informational purposes. This occurs as part of the configure_irods_testing, which is called from the various scripts for running tests.

**Comment by alanking** [comment]
I created #91 for the documentation exercise. Closing this one.
